spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.122/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.31.122
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wx7ecf0954bb8df674
  mpAppSecret: 16850ec49e5ae2bf02613776454ca0c5
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://jinyang.vaiwan.cn/sell/pay/notify
  templateId:
    orderStatus: 5qLZfS-l40SMqz9NOwhpvwfqx7ck1dc4VwCvdzq6IN4

projectUrl:
  wechatMpAuthorize: http://jinyang.vaiwan.cn
  wechatOpenAuthorize: http://jinyang.vaiwan.cn
  sell: http://jinyang.vaiwan.cn
